### ISSUE TITLE
Code Code Code!!!

### ISSUE THREAD

**Issue by SandLYJ** [Eniac-Xie/FuseTeacher#1]
I am very interested in your idea, can you realse your source code?

**Comment by Eniac-Xie** [comment]
@LYJhere Thank you for your interest in our work. The code will be released within a month, and we will also try our best to do it sooner.

**Comment by SandLYJ** [comment]
Thanks!

**Comment by Eniac-Xie** [comment]
Hello, the code has been updated. Thank you for your attention to our work.
